CREATE TABLE CSUF_MEMBER(
   CWID INT NOT NULL PRIMARY KEY,
   FIRST_NAME VARCHAR(20) NOT NULL,
   LAST_NAME  VARCHAR(20) NOT NULL,
   EMAIL VARCHAR(30) NOT NULL,
   PASSWORD VARCHAR(20) NOT NULL,
   FACULTY_ID INT,
   STUDENT_ID INT,
   ADMIN_ID INT,
   DEPARTMENT_NUM CHAR(4) NOT NULL,
   ACCOUNT_ID INT NOT NULL
);

CREATE TABLE FACULTY(
   FID INT NOT NULL PRIMARY KEY,
   COURSE_SESSION_ID INT
);

CREATE TABLE STUDENT(
   SID INT NOT NULL PRIMARY KEY,
   COURSE_SESSION_ID INT
);

CREATE TABLE ADMIN(
   AID INT NOT NULL PRIMARY KEY
);

CREATE TABLE DEPARTMENT(
   DNUM CHAR(4) NOT NULL PRIMARY KEY,
   COURSE_SCHEDULE_ID INT
);

CREATE TABLE ACCOUNT(
   ACOUNT_ID INT NOT NULL PRIMARY KEY
);

CREATE TABLE COURSE_SESSION(
   CSNUM INT NOT NULL PRIMARY KEY,
   COURSE_NUM CHAR(7) NOT NULL,
   DETAILS LONGTEXT
);

CREATE TABLE UPLOAD(
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR(30) NOT NULL,
   TYPE VARCHAR(30) NOT NULL,
   SIZE INT NOT NULL,
   CONTENT LONGBLOB NOT NULL
);

CREATE TABLE TEACH(
   FID INT NOT NULL,
   COURSE_NUM CHAR(7) NOT NULL,
   COURSE_MATERIAL_ID INT NOT NULL,
   PRIMARY KEY(FID, COURSE_NUM, COURSE_MATERIAL_ID)
);

CREATE TABLE COURSE(
   CNUM CHAR(7) NOT NULL PRIMARY KEY,
   DETAILS LONGTEXT
);

CREATE TABLE COURSE_MATERIAL(
   CMID INT NOT NULL PRIMARY KEY,
   DOCUMENT_UP INT
);

CREATE TABLE ENROLL(
   SID INT NOT NULL,
   COURSE_SECTION_NUM INT NOT NULL,
   DELIVER_ID INT NOT NULL,
   GRADES FLOAT,
   PRIMARY KEY(SID, COURSE_SECTION_NUM, DELIVER_ID)
);

CREATE TABLE COURSE_SCHEDULE(
   COURSE_SCHEDULE_ID INT NOT NULL PRIMARY KEY,
   COURSE_NUM CHAR(7)
);

CREATE TABLE DELIVERABLE(
   DELIVER_ID INT NOT NULL PRIMARY KEY,
   MIDTERM INT,
   FINAL_EXAM INT,
   TERM_PROJECT INT,
   HOMEWORK INT
);

CREATE TABLE MIDTERM(
   MIDTERM_ID INT NOT NULL PRIMARY KEY,
   SCORE FLOAT
);

CREATE TABLE FINAL_EXAM(
   FINAL_EXAM_ID INT NOT NULL PRIMARY KEY,
   SCORE FLOAT
);

CREATE TABLE TERM_PROJECT(
   TERM_PROJECT_ID INT NOT NULL PRIMARY KEY,
   SCORE FLOAT,
   PROJECT_UP INT
);

CREATE TABLE HOMEWORK(
   HOMEWORK INT NOT NULL PRIMARY KEY,
   SCORE FLOAT,
   DOCUMENT_UP INT
);
